/**
 * Copyright (c) 2018-2019, Eric 黄鑫 (ninemm@126.com).
 * <p>
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jpress.module.crawler.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScheduleTask<M extends BaseScheduleTask<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTaskId(java.lang.String taskId) {
		set("task_id", taskId);
	}
	
	public java.lang.String getTaskId() {
		return getStr("task_id");
	}

	public void setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
	}
	
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}

	public void setTaskDescription(java.lang.String taskDescription) {
		set("task_description", taskDescription);
	}
	
	public java.lang.String getTaskDescription() {
		return getStr("task_description");
	}

	public void setTaskClass(java.lang.String taskClass) {
		set("task_class", taskClass);
	}
	
	public java.lang.String getTaskClass() {
		return getStr("task_class");
	}

	public void setCron(java.lang.String cron) {
		set("cron", cron);
	}
	
	public java.lang.String getCron() {
		return getStr("cron");
	}

	public void setPageSize(java.lang.Integer pageSize) {
		set("page_size", pageSize);
	}

	public java.lang.Integer getPageSize() {
		return getInt("page_size");
	}

	public void setIsActive(java.lang.Boolean isActive) {
		set("is_active", isActive);
	}
	
	public java.lang.Boolean getIsActive() {
		return get("is_active");
	}

	public void setIsStart(java.lang.Boolean isStart) {
		set("is_start", isStart);
	}
	
	public java.lang.Boolean getIsStart() {
		return get("is_start");
	}

	public void setIsDaemon(java.lang.Boolean isDaemon) {
		set("is_daemon", isDaemon);
	}
	
	public java.lang.Boolean getIsDaemon() {
		return get("is_daemon");
	}

	public void setIsDistributed(java.lang.Boolean isDistributed) {
		set("is_distributed", isDistributed);
	}
	
	public java.lang.Boolean getIsDistributed() {
		return get("is_distributed");
	}

	public void setLastExecuteTime(java.util.Date lastExecuteTime) {
		set("last_execute_time", lastExecuteTime);
	}
	
	public java.util.Date getLastExecuteTime() {
		return get("last_execute_time");
	}

	public void setLastKeywordId(java.lang.Long lastKeywordId) {
		set("last_keyword_id", lastKeywordId);
	}
	
	public java.lang.Long getLastKeywordId() {
		return getLong("last_keyword_id");
	}

	public void setLastPageNum(java.lang.Integer lastPageNum) {
		set("last_page_num", lastPageNum);
	}
	
	public java.lang.Integer getLastPageNum() {
		return getInt("last_page_num");
	}

	public void setTotalNum(java.lang.Long totalNum) {
		set("total_num", totalNum);
	}
	
	public java.lang.Long getTotalNum() {
		return getLong("total_num");
	}

	public void setSearchType(java.lang.String searchType) {
		set("search_type", searchType);
	}
	
	public java.lang.String getSearchType() {
		return getStr("search_type");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

}
