/*
 * Copyright (c) 2018-2019, Eric 黄鑫 (ninemm@126.com).
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jpress.module.crawler.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProxyInfo<M extends BaseProxyInfo<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setIp(String ip) {
		set("ip", ip);
	}

	public String getIp() {
		return getStr("ip");
	}

	public void setPort(Integer port) {
		set("port", port);
	}

	public Integer getPort() {
		return getInt("port");
	}

	public void setLocation(String location) {
		set("location", location);
	}

	public String getLocation() {
		return getStr("location");
	}

	public void setEnable(Boolean isEnable) {
		set("is_enable", isEnable);
	}

	public Boolean getEnable() {
		return get("is_enable");
	}

	public void setVerified(Boolean isVerified) {
		set("is_verified", isVerified);
	}

	public Boolean getVerified() {
		return get("is_verified");
	}

	public void setResponse(Float response) {
		set("response", response);
	}

	public Float getResponse() {
		return getFloat("response");
	}

	public void setVerifyTime(java.util.Date verifyTime) {
		set("verify_time", verifyTime);
	}

	public java.util.Date getVerifyTime() {
		return get("verify_time");
	}

	public void setCrawlerTime(java.util.Date crawlerTime) {
		set("crawler_time", crawlerTime);
	}

	public java.util.Date getCrawlerTime() {
		return get("crawler_time");
	}

	public void setInvalidTime(Long invalidTime) {
		set("invalid_time", invalidTime);
	}

	public Long getInvalidTime() {
		return getLong("invalid_time");
	}

	public void setLastSurviveTime(Long lastSurviveTime) {
		set("last_survive_time", lastSurviveTime);
	}

	public Long getLastSurviveTime() {
		return getLong("last_survive_time");
	}

	public void setProtocol(String protocol) {
		set("protocol", protocol);
	}

	public String getProtocol() {
		return getStr("protocol");
	}

	public void setAnonymityType(String anonymityType) {
		set("anonymity_type", anonymityType);
	}

	public String getAnonymityType() {
		return getStr("anonymity_type");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return getStr("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return getStr("password");
	}

	public void setMethod(String method) {
		set("method", method);
	}

	public String getMethod() {
		return getStr("method");
	}

	public void setWebsite(String website) {
		set("website", website);
	}

	public String getWebsite() {
		return getStr("website");
	}

	public void setIsp(String isp) {
		set("isp", isp);
	}

	public String getIsp() {
		return getStr("isp");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}
	
	public java.util.Date getModified() {
		return get("modified");
	}

}
