/**
 * Copyright (c) 2018-2019, Eric 黄鑫 (ninemm@126.com).
 * <p>
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jpress.module.crawler.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.crawler.model.base.BaseScheduleTask;
import it.sauronsoftware.cron4j.SchedulerListener;
import it.sauronsoftware.cron4j.TaskExecutor;

import java.util.Date;

/**
 * Generated by Jboot.
 */
@Table(tableName = "c_schedule_task", primaryKey = "id")
public class ScheduleTask extends BaseScheduleTask<ScheduleTask> implements SchedulerListener {

    public Boolean isActive(){
        return getIsActive() !=null && getIsActive();
    }

    public Boolean isStart(){
        return getIsStart() !=null && getIsStart();
    }

    public Boolean isDistributed(){
        return getIsDistributed() !=null && getIsDistributed();
    }

    public Boolean isDaemon(){
        return getIsDaemon() !=null && getIsDaemon();
    }

    public void taskLaunching(TaskExecutor executor) {

    }

    public void taskSucceeded(TaskExecutor executor) {
        setLastExecuteTime(new Date());
        update();
    }

    public void taskFailed(TaskExecutor executor, Throwable exception) {

    }

}
